name: Run Examples

on: push

jobs:
  run-examples:
    runs-on: self-hosted
    container:
      image: ubuntu:24.04
    if: github.event.pull_request.draft == false
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.12'
            case-path: '.'
          - python-version: '3.13'
            case-path: 'Electromagnetics/Compumag-Team1b-Felix-Cylinder'
          - python-version: '3.14'
            case-path: 'Electromagnetics/Compumag-Team1b-Felix-Cylinder'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y libgomp1

    - name: Set MUFEM version from VERSION file
      run: |
        echo "MUFEM_VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Install Python dependencies
      run: |
        pip install mufem==$MUFEM_VERSION
        pip install -r requirements.txt
        pip install -i https://gmsh.info/python-packages-dev-nox --force-reinstall --no-cache-dir gmsh

    - name: Run the examples
      run: |
        python3 ./run_cases.py ${{ matrix.case-path }}
